# Generated by Django 5.2.12 on 2026-07-03 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access this app"),
                    (
                        "add_corp_owner",
                        "Can add or update the ESI token for a corporation",
                    ),
                    ("view_corp", "Can view freelance jobs for their own corporation"),
                    ("view_alliance", "Can view freelance jobs for their own alliance"),
                    ("view_faction", "Can view freelance jobs for their own faction"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disabled owners are skipped by the sync task",
                    ),
                ),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "jobs_cursor",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ESI pagination cursor for the freelance jobs listing, advanced as new/updated jobs are discovered",
                        max_length=255,
                    ),
                ),
                (
                    "corporation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelance_tracker_owner",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="FreelanceJob",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Unspecified", "Unspecified"),
                            ("Active", "Active"),
                            ("Closed", "Closed"),
                            ("Completed", "Completed"),
                            ("Expired", "Expired"),
                            ("Deleted", "Deleted"),
                        ],
                        default="Unspecified",
                        max_length=32,
                    ),
                ),
                (
                    "career",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Unspecified", "Unspecified"),
                            ("Explorer", "Explorer"),
                            ("Industrialist", "Industrialist"),
                            ("Enforcer", "Enforcer"),
                            ("Soldier of Fortune", "Soldier Of Fortune"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "creator_character_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("expires", models.DateTimeField(blank=True, null=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                ("progress_current", models.BigIntegerField(default=0)),
                ("progress_desired", models.BigIntegerField(default=0)),
                ("reward_initial", models.FloatField(default=0)),
                ("reward_remaining", models.FloatField(default=0)),
                ("configuration_method", models.CharField(blank=True, max_length=64)),
                ("configuration_version", models.PositiveIntegerField(default=1)),
                (
                    "configuration_parameters",
                    models.JSONField(blank=True, default=dict),
                ),
                ("contribution", models.JSONField(blank=True, default=dict)),
                ("access_and_visibility", models.JSONField(blank=True, default=dict)),
                ("last_modified", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="freelance_tracker.owner",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="FreelanceJobParticipant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.PositiveIntegerField()),
                ("character_name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Unspecified", "Unspecified"),
                            ("Committed", "Committed"),
                            ("Kicked", "Kicked"),
                            ("Resigned", "Resigned"),
                        ],
                        default="Unspecified",
                        max_length=32,
                    ),
                ),
                ("contributed", models.BigIntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="freelance_tracker.freelancejob",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("job", "character_id")},
            },
        ),
    ]
