# Generated by Django 5.2.15 on 2026-07-04 08:58

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("freelance_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    (
                        "add_corp_owner",
                        "Can add or update the ESI token for a corporation",
                    ),
                    ("view_corp", "Can view freelance jobs for their own corporation"),
                    ("view_alliance", "Can view freelance jobs for their own alliance"),
                    ("view_faction", "Can view freelance jobs for their own faction"),
                    (
                        "view_participants",
                        "Can view a job's participants in the detail view",
                    ),
                ),
            },
        ),
    ]
